### ISSUE TITLE
Docs for usage

### ISSUE THREAD

**Issue by shadowzick** [meteor-helium/instagram#1]
Please put some docs on how to use the API. thanks!

**Comment by butane** [comment]
Please see the Official Meteor accounts docs (https://guide.meteor.com/accounts.html).
This package works very similar to other core packages for login providers.

**Comment by butane** [comment]
This package does not do anything new and I feel it does not deserve docs on its own.

**Comment by bhdzllr** [comment]
Hello,
thank you for the package.

I've added it to my project and I've  spent some time figuring out how I get the data, here is how I did it:

```JavaScript
import { Instagram } from 'meteor/helium:instagram';

// On the client
Instagram.requestCredential((tokenOrError) => {
	let secret = Package.oauth.OAuth._retrieveCredentialSecret(tokenOrError);

	Meteor.call('updateInstagramData', tokenOrError, secret, () => {
		if (err) {
			console.log(err.reason);
		} else {
			console.log('Instagram authorization done');
		}
	})
});

// On the Server
updateInstagramData(token, secret) {
	let credential = Instagram.retrieveCredential(token, secret);
	// "credential" is now an object with the data from Instagram
}
```

This part doesn't look very clean, but it works:

```JavaScript
let secret = Package.oauth.OAuth._retrieveCredentialSecret(tokenOrError);
```

Maybe that helps someone.
